game_instantMode=true
graphics_zoomChange=0.05
graphics_framerate=60
graphics_windowPosition=NONE
graphics_pixelPerMeter=32.0
graphics_windowHeight=576
graphics_colorScheme=Gnome
graphics_pixelMultiplication=1
graphics_screenRecordingNFrames=2
graphics_windowWidth=768
sound_musicVolume=0.5
sound_soundVolume=0.5
debug_renderAABBs=false
debug_actorCoordinates=false
debug_enabled=false
debug_renderActors=true
debug_useANSIcolors=true
coordinatesystem_labelsOnIntersections=false
coordinatesystem_linesNMeter=-1
