---
name: Run tests

on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          submodules: true

      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # https://github.com/marketplace/actions/setup-just
      - uses: extractions/setup-just@v3

      - name: Sync the assets with some resources folder
        run: just assets_sync_resources

      - name: Install protobuf-compiler for jbox2d serialization module
        run: sudo apt install -y protobuf-compiler

      - name: Run the tests using Maven
        run: mvn test
